version: '3.4'

services:
  spring-order:
    image: spring-microservices/order
    container_name: spring-order
    environment:
      - DB_URL=/dborder
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
    ports:
      - "18081:8080"
    build:
      context: ./microservice-spring-order
      dockerfile: Dockerfile
  spring-shipping:
    image: spring-microservices/shipping
    container_name: spring-shipping
    environment:
      - DB_URL=/dbshipping
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
      - ORDER_URL=http://spring-order:8080/feed
    ports:
      - "18083:8080"
    links:
      - spring-order
    build:
      context: ./microservice-spring-shipping
      dockerfile: Dockerfile
  spring-invoicing:
    image: spring-microservices/invoicing
    container_name: spring-invoicing
    environment:
      - DB_URL=/dbinvoicing
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
      - ORDER_URL=http://spring-order:8080/feed
    ports:
      - "18082:8080"
    links:
      - spring-order
    build:
      context: ./microservice-spring-invoicing
      dockerfile: Dockerfile
